name: Gradle CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew 
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build JAR
        run: ./gradlew build -x test
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: build/libs/*.jar

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: application-jar
          path: ./build/libs
      - name: List files after download
        run: ls -la ./build/libs/
      - name: Deploy JAR to Staging Server with Password
        env:
          SERVER_HOST: 89.250.70.43
          SERVER_USER: root
          SERVER_PASSWORD: Kyrgyzstanym01!
        run: |
          # Install sshpass to allow password-based SSH
          sudo apt-get update && sudo apt-get install -y sshpass
          
          # Ensure the target directory exists
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p /opt/trpo"
          
          # Copy the JAR file
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no ./build/libs/travel-0.0.1-SNAPSHOT.jar $SERVER_USER@$SERVER_HOST:/opt/trpo/
          
          # Verify the file and restart the service
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
            ls -la /opt/trpo/travel-0.0.1-SNAPSHOT.jar &&
            chmod 755 /opt/trpo/travel-0.0.1-SNAPSHOT.jar &&
            sudo systemctl restart test.service
          "

